### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by blakbox23**
In this project we ;

- Generated and customized models, views, and controllers to handle events
- Created many to many associations (`has_many:through`) to connect the models
- Added Rspec and Capybara for testing

### CODE REVIEW

**Review by george-shammar — CHANGES_REQUESTED** [review]
### **STATUS:CHANGES REQUIRED** :recycle: :recycle: :construction: 

Good job with this project, team.

Your application works and your repo looks professional.

Please see below few changes that are required to get this project approved.

- [x] There is no way to access your users' show page on the page. 
- [x] The user's show page should display events the user has created and events that the user is attending, to be separated in past and upcoming.
- [x] Navigation links should be present at the top of the page.
- [x] When I clicked on the attend event button twice, the page throws an error. `undefined method `edirect_to' `. It seems you have a typographical error in your controller.
- [x] Index action in your Event Controllers should list past events, i.e. @past_events = Event.previous_events.
- [x] Index action in your Event Controllers should list upcoming events, i.e. `@upcoming_events` = `Event.upcoming_events.`
- [x] show action of your User Controller should list events previously attended by user using event model scope, i.e. @past_events = current_user.attended_events.previous 
- [x] show action of your User Controller should list upcoming events previously attended by user using event model scope, i.e. `@upcoming_events` = `current_user.attended_events.upcoming`.
- [x] Some of your tests are failing.
- [x] Include integration tests for your authentication. You may use Rspec and Capybara.
- [ ] Please test your associations as well.

[OPTION]

- [ ] Please remove all logic from your view files.
- [ ] In your application, anyone could delete an event irrespective of whether they created it or not. The event creator should only be able to delete an event.

Please make these changes and submit another CRR when you're ready.

Drop your message here if you require clarification.

Cheers and happy coding. :+1: :smile:

**Review by taiwo2 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED ♻️ 🚧
@blakbox23 Great start and Weldone for trying to implement what the previous Code Reviewer suggested, however changes are required to get your project approved
#### highlights

- [x] There is no way to access your users' show page on the page. 👍🏻 
- [x]  Navigation links should be present at the top of the page. 👍🏻 
- [x]  When I clicked on the attend event button twice, the page throws an error. undefined method edirect_to' `. It seems you have a typographical error in your controller. 👍🏻 
- [x]  Some of your tests are failing. 👍🏻 
- [x]  Include integration tests for your authentication. You may use Rspec and Capybara. 👍🏻 
#### Improve 

- [x] show action of your User Controller should list events previously attended by user using event model scope, i.e. @past_events = current_user.attended_events.previous
- [x]  show action of your User Controller should list upcoming events previously attended by user using event model scope, i.e. @upcoming_events = current_user.attended_events.upcoming
- [x] Logged in user can create new event **(covered by automated tests)** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_can_create_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations)). I can't create an Event
- [x] Event's index page displays past and upcoming events lists **(covered by automated tests)** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
- [x] The event's show page displays the list of attendants **(covered by automated tests)** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/events_attendees_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
- [x] The user's show page displays events the user has created and events that the user is attending to separated in past and upcoming **(covered by automated tests)** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
 ### once significant changes made kindly request for another review

**Comment by Deepakdanger** [comment]
All Changes are already done 👍

**Review by oloomoses — APPROVED** [review]
## Congratulations, Project Approved. :muscle: :tada: :clap: 
**Hello team,
Great job working on the suggested changes from the previous review.
You have passed all the requirements for this project :muscle:**
## Highlights
- Logged in user can create a new event :heavy_check_mark:
- Event's index page displays past and upcoming events lists :heavy_check_mark:
- Well done on the linter/rubocop configuration :muscle:
- The event's show page displays the list of attendants :heavy_check_mark: 
- The user's show page displays events the user has created and events that the user is attending to separated in past and upcoming :heavy_check_mark:
- Great job on the tests :muscle:

## Nice to have
- [ ] Kindly use `date_field` for the new event form. This way a user can easily choose past f future dates when creating an event.

**Feel free to merge and close this pull request. after working on the nice to have requirement suggested above**

**I wish you the best in your next project and see you at the top :rocket:** 
#### Happy Coding
_Slack: Oloo Moses_

**Pull request merged**
